version: '3.8'

services:
  nestjs_app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - '5000:5000'
    networks:
      - backend-network
    depends_on:
      - postgres
    environment:
      NODE_ENV: production 
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: tundrax_db
      JWT_SERVER_SECRET: sUp4hS3cr37kE9c0D3
      TOKEN_LIFETIME_IN_SECONDS : 1h

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    networks:
      - backend-network
    environment:
      POSTGRES_DB: tundrax_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  postgres_test:
    image: postgres
    ports:
      - '5434:5432'
    networks:
      - backend-network
    environment:
      POSTGRES_DB: tundrax_test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
networks:
  backend-network:
    driver: bridge
