version: '3.8'

services:
  postgres_test:
    image: postgres
    ports:
      - '54325:5432'
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

  postgres_dev:
    image: postgres
    ports:
      - '54326:5432'
    environment:
      POSTGRES_DB: tundrax_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password